
name: Step 16 Practice

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/**'

  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-ci:
    uses: ./.github/workflows/shared-ci.yml
    with:
      java-version: '21'

  composite-action:
    runs-on: ubuntu-latest
    needs: reusable-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run composite action
        uses: ./.github/actions/hello
        with:
          app-name: github-actions-learning